### ISSUE TITLE
Core dumped when compiling

### ISSUE THREAD

**Issue by WilliamWangPeng** [ttsiodras/renderer#5]
Dear Author
    It's an honor to write an issue here and I use ubuntu18.04 when compiling the renderer, the dependencies I have installed like libsdl1.2-dev, and as followed the commands here:
    ./configure  
    make  
    cd 3D-Objects
    ../src/renderer -b chessboard.tri

but it shows core dumped, originally " Segmentation fault (core dumped)
 ", Do you know why?

Thank you
Best Regards
William

**Comment by ttsiodras** [comment]
Hi William.

I have used the renderer in many environments - and have never experienced this.
Can you  try running `make bench` right after your `make`?
This will use the renderer with memory-only "display" for benchmarking - and will display the achieved frame rate in 5 successive tests.

If this works, then I presume your originally reported crash has something to do with your graphics card setup.
I cannot offer any more help beyond this, given the lack of information - "I used Ubuntu 18.04" is not really useful, since I can also say that I have used the renderer in all sorts of OSes (even non-Linux ones) with no issues...
